name: time_gpt_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - scipy=1.16.0
  - scikit-learn=1.7.0
  - python-dotenv=1.1.1
  - psutil=7.0.0
  - pillow=11.3.0
  - pandas=2.3.1
  - matplotlib=3.10.3
  - dask=2025.5.1
  - pip
  - pip:
      - nixtla==0.6.6
